name: CI

on:
  push:
    branches: [master]
  pull_request: ~

env:
  FORCE_COLOR: 1

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: pip install -r requirements.txt
    - uses: pre-commit/action@v3.0.0
